version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to ECR
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 989239674376.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build started
      - docker build -t brain-app .
      - docker tag brain-app:latest 989239674376.dkr.ecr.us-east-1.amazonaws.com/brain-app:latest

  post_build:
    commands:
      - echo Pushing image
      - docker push 989239674376.dkr.ecr.us-east-1.amazonaws.com/brain-app:latest
